#!/bin/bash
#
# This script is part of the testbus NFS suite
#
# Copyright (C) 2013-2014 Olaf Kirch <okir@suse.de>
#

. $0.init

##################################################################
# Basic testing of NFS mounts
##################################################################
$0.mount

##################################################################
# Test export handling
##################################################################
$0.export

##################################################################
# Run a standard set of tests exercising different operations
# of the NFS protocol, for each NFS protocol version
##################################################################
$0.fileops

##################################################################
# Data consistency and locking
##################################################################
$0.coherence

testbus_exit
